-- plugins/bufferline.lua
return {
  'akinsho/bufferline.nvim',
  version = '*',
  dependencies = { 'nvim-tree/nvim-web-devicons' },
  --   event = 'VeryLazy',
  --   opts = {
  --     style_preset = require('bufferline').style_preset.default,
  --     themable = true,
  --     numbers = 'ordinal',
  --     close_command = 'bdelete! %d',
  --     right_mouse_command = 'bdelete! %d',
  --     left_mouse_command = 'buffer %d',
  --     middle_mouse_command = nil,
  --     indicator = {
  --       icon = '▎',
  --       style = 'icon',
  --     },
  --     buffer_close_icon = '󰅖',
  --     modified_icon = '●',
  --     close_icon = '',
  --     left_trunc_marker = '',
  --     right_trunc_marker = '',
  --     name_formatter = function(buf)
  --       return buf.name
  --     end,
  --     max_name_length = 18,
  --     max_prefix_length = 15,
  --     truncate_names = true,
  --     tab_size = 18,
  --     diagnostics = 'nvim_lsp',
  --     diagnostics_update_in_insert = false,
  --     diagnostics_update_on_event = true,
  --     diagnostics_indicator = function(count, level, diagnostics_dict, context)
  --       return '(' .. count .. ')'
  --     end,
  --     custom_filter = function(buf_number, buf_numbers)
  --       if vim.bo[buf_number].filetype ~= 'qf' then
  --         return true
  --       end
  --     end,
  --     offsets = {
  --       {
  --         filetype = 'neo-tree',
  --         text = 'File Explorer',
  --         text_align = 'center',
  --         separator = true,
  --       },
  --     },
  --     color_icons = true,
  --     get_element_icon = function(element)
  --       local icon, hl = require('nvim-web-devicons').get_icon_by_filetype(element.filetype, { default = true })
  --       return icon, hl
  --     end,
  --     show_buffer_icons = true,
  --     show_buffer_close_icons = true,
  --     show_close_icon = true,
  --     show_tab_indicators = true,
  --     show_duplicate_prefix = true,
  --     duplicates_across_groups = true,
  --     persist_buffer_sort = true,
  --     move_wraps_at_ends = true,
  --     separator_style = 'slant',
  --     enforce_regular_tabs = false,
  --     always_show_bufferline = true,
  --     auto_toggle_bufferline = false,
  --     hover = {
  --       enabled = true,
  --       delay = 200,
  --       reveal = { 'close' },
  --     },
  --     sort_by = function(a, b)
  --       return vim.fn.getftime(a.path) > vim.fn.getftime(b.path)
  --     end,
  --     pick = {
  --       alphabet = 'abcdefghijklmopqrstuvwxyzABCDEFGHIJKLMOPQRSTUVWXYZ1234567890',
  --     },
  --   },
}
