-- SQL Keywords Hash Table (optimized for O(1) lookup)
local sql_keywords_set = {
  -- Data Definition Language (DDL)
  ['create'] = true,
  ['alter'] = true,
  ['drop'] = true,
  ['truncate'] = true,
  ['comment'] = true,
  ['rename'] = true,

  -- Data Manipulation Language (DML)
  ['select'] = true,
  ['insert'] = true,
  ['update'] = true,
  ['delete'] = true,
  ['merge'] = true,
  ['upsert'] = true,

  -- Data Control Language (DCL)
  ['grant'] = true,
  ['revoke'] = true,
  ['deny'] = true,

  -- Transaction Control Language (TCL)
  ['commit'] = true,
  ['rollback'] = true,
  ['savepoint'] = true,
  ['begin'] = true,
  ['start'] = true,
  ['end'] = true,

  -- Query Structure
  ['from'] = true,
  ['where'] = true,
  ['having'] = true,
  ['order'] = true,
  ['group'] = true,
  ['by'] = true,
  ['limit'] = true,
  ['offset'] = true,
  ['distinct'] = true,
  ['all'] = true,
  ['top'] = true,
  ['fetch'] = true,
  ['first'] = true,
  ['last'] = true,
  ['rows'] = true,
  ['only'] = true,

  -- Joins
  ['join'] = true,
  ['inner'] = true,
  ['left'] = true,
  ['right'] = true,
  ['full'] = true,
  ['outer'] = true,
  ['cross'] = true,
  ['natural'] = true,
  ['on'] = true,
  ['using'] = true,

  -- Set Operations
  ['union'] = true,
  ['intersect'] = true,
  ['except'] = true,
  ['minus'] = true,

  -- Conditional Logic
  ['case'] = true,
  ['when'] = true,
  ['then'] = true,
  ['else'] = true,
  ['if'] = true,
  ['elseif'] = true,
  ['endif'] = true,

  -- Logical Operators
  ['and'] = true,
  ['or'] = true,
  ['not'] = true,
  ['exists'] = true,
  ['in'] = true,
  ['between'] = true,
  ['like'] = true,
  ['ilike'] = true,
  ['is'] = true,
  ['null'] = true,
  ['true'] = true,
  ['false'] = true,

  -- Comparison Operators
  ['any'] = true,
  ['some'] = true,

  -- Subqueries
  ['with'] = true,
  ['recursive'] = true,
  ['cte'] = true,
  ['over'] = true,
  ['partition'] = true,
  ['window'] = true,

  -- Aggregate Functions
  ['count'] = true,
  ['sum'] = true,
  ['avg'] = true,
  ['min'] = true,
  ['max'] = true,
  ['stddev'] = true,
  ['variance'] = true,

  -- Window Functions
  ['row_number'] = true,
  ['rank'] = true,
  ['dense_rank'] = true,
  ['ntile'] = true,
  ['lag'] = true,
  ['lead'] = true,
  ['first_value'] = true,
  ['last_value'] = true,

  -- String Functions
  ['concat'] = true,
  ['substring'] = true,
  ['substr'] = true,
  ['length'] = true,
  ['upper'] = true,
  ['lower'] = true,
  ['trim'] = true,
  ['ltrim'] = true,
  ['rtrim'] = true,
  ['replace'] = true,
  ['regexp'] = true,
  ['rlike'] = true,

  -- Date/Time Functions
  ['now'] = true,
  ['current_date'] = true,
  ['current_time'] = true,
  ['current_timestamp'] = true,
  ['extract'] = true,
  ['date_part'] = true,
  ['interval'] = true,

  -- Casting and Conversion
  ['cast'] = true,
  ['convert'] = true,
  ['coalesce'] = true,
  ['nullif'] = true,
  ['isnull'] = true,
  ['nvl'] = true,

  -- Database Objects
  ['database'] = true,
  ['schema'] = true,
  ['table'] = true,
  ['view'] = true,
  ['index'] = true,
  ['sequence'] = true,
  ['trigger'] = true,
  ['function'] = true,
  ['procedure'] = true,
  ['package'] = true,
  ['synonym'] = true,

  -- Constraints
  ['primary'] = true,
  ['foreign'] = true,
  ['key'] = true,
  ['unique'] = true,
  ['check'] = true,
  ['default'] = true,
  ['references'] = true,
  ['constraint'] = true,
  ['cascade'] = true,
  ['restrict'] = true,
  ['set'] = true,

  -- Data Types
  ['integer'] = true,
  ['int'] = true,
  ['bigint'] = true,
  ['smallint'] = true,
  ['tinyint'] = true,
  ['decimal'] = true,
  ['numeric'] = true,
  ['float'] = true,
  ['real'] = true,
  ['double'] = true,
  ['precision'] = true,
  ['money'] = true,
  ['char'] = true,
  ['varchar'] = true,
  ['text'] = true,
  ['nchar'] = true,
  ['nvarchar'] = true,
  ['ntext'] = true,
  ['date'] = true,
  ['time'] = true,
  ['datetime'] = true,
  ['timestamp'] = true,
  ['year'] = true,
  ['boolean'] = true,
  ['bool'] = true,
  ['binary'] = true,
  ['varbinary'] = true,
  ['blob'] = true,
  ['clob'] = true,
  ['json'] = true,
  ['uuid'] = true,

  -- Modifiers
  ['unsigned'] = true,
  ['zerofill'] = true,
  ['auto_increment'] = true,
  ['serial'] = true,
  ['identity'] = true,
  ['generated'] = true,
  ['always'] = true,
  ['stored'] = true,
  ['virtual'] = true,

  -- Storage and Performance
  ['clustered'] = true,
  ['nonclustered'] = true,
  ['hash'] = true,
  ['btree'] = true,
  ['gist'] = true,
  ['gin'] = true,
  ['analyze'] = true,
  ['explain'] = true,
  ['describe'] = true,
  ['desc'] = true,
  ['show'] = true,
  ['vacuum'] = true,

  -- Permissions and Security
  ['role'] = true,
  -- ['user'] = true,
  ['login'] = true,
  ['password'] = true,
  ['encrypted'] = true,
  ['unencrypted'] = true,

  -- Advanced Features
  ['materialized'] = true,
  ['temporary'] = true,
  ['temp'] = true,
  ['global'] = true,
  ['local'] = true,
  ['session'] = true,
  ['transaction'] = true,
  ['isolation'] = true,
  ['level'] = true,
  ['read'] = true,
  ['write'] = true,
  ['committed'] = true,
  ['uncommitted'] = true,
  ['repeatable'] = true,
  ['serializable'] = true,

  -- PostgreSQL Specific
  ['returning'] = true,
  ['conflict'] = true,
  ['nothing'] = true,
  ['excluded'] = true,
  ['concurrently'] = true,

  -- MySQL Specific
  ['ignore'] = true,
  ['duplicate'] = true,
  ['straight_join'] = true,
  ['force'] = true,

  -- Common Extensions
  ['copy'] = true,
  ['import'] = true,
  ['export'] = true,
  ['backup'] = true,
  ['restore'] = true,
  ['optimize'] = true,
  ['repair'] = true,
  ['lock'] = true,
  ['unlock'] = true,
  ['flush'] = true,
  ['reset'] = true,
  ['load'] = true,
  ['unload'] = true,
}

return sql_keywords_set
